name: Auto Comment on New Issues

on:
  issues:
    types:
      - opened

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: Comment on New Issue
      uses: actions/github-script@v9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { owner, repo } = context.repo;
          const issueNumber = context.payload.issue.number;
          const commentBody = `
                Obrigado por querer melhorar o repositório! Vamos investigar e entrar em contato com você, mas tenha calma, temos outras demandas e coisas para fazer. Enquanto isso, de uma olhada nos  [problemas fechados](https://github.com/felipementel/apis-hub-for-developers/issues?q=is%3AsuSue+is%3Aclosed), caso sua pergunta já tenha sido respondida. Não se esqueça de fornecer informações adicionais, se necessário (por exemplo, logs, etc.).
                Sempre que for viável, não hesite em enviar uma solicitação de pull request (PR) seguindo o padrão. Agradecemos muito! Avaliaremos e incorporaremos com prazer suas mudanças.
          `;

          await github.rest.issues.createComment({
            owner,
            repo,
            issue_number: issueNumber,
            body: commentBody,
          });
